[project]
name = "datasus-sinan"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = [
    "datasus-dbc>=0.1.3",
    "nbformat>=5.10.4",
    "pandas>=2.3.3",
    "typer>=0.21.0",
]

[dependency-groups]
dev = [
    "black>=25.12.0",
]
